// <auto-generated />
using System;
using System.Collections.Generic;
using BenefitsIntelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BenefitsIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BenefitsIntelligence.Domain.Organisations.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Organisations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Demo Organisation"
                        });
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.BenefitPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AnnualExcess")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AnnualPremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BenefitType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("DependantsAllowed")
                        .HasColumnType("bit");

                    b.Property<bool?>("DependantsIncluded")
                        .HasColumnType("bit");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("RenewalDate")
                        .HasColumnType("date");

                    b.Property<string>("SchemeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("OrganisationId", "CreatedAt");

                    b.ToTable("BenefitPolicies");
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.CoverageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Covered")
                        .HasColumnType("bit");

                    b.Property<string>("Limit")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SessionLimit")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Assessment", "BenefitsIntelligence.Domain.Policies.CoverageItem.Assessment#FactAssessment", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Confidence")
                                .HasColumnType("float")
                                .HasColumnName("Confidence");

                            b1.Property<int>("ReviewReasons")
                                .HasColumnType("int")
                                .HasColumnName("ReviewReasons");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Evidence", "BenefitsIntelligence.Domain.Policies.CoverageItem.Assessment#FactAssessment.Evidence#Evidence", b2 =>
                                {
                                    b2.Property<int>("PageEnd")
                                        .HasColumnType("int")
                                        .HasColumnName("EvidencePageEnd");

                                    b2.Property<int>("PageStart")
                                        .HasColumnType("int")
                                        .HasColumnName("EvidencePageStart");

                                    b2.Property<string>("Quote")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("nvarchar(2000)")
                                        .HasColumnName("EvidenceQuote");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("PolicyId", "Type")
                        .IsUnique();

                    b.ToTable("CoverageItems", (string)null);
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.DocumentPage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "PageNumber")
                        .IsUnique();

                    b.ToTable("PolicyDocumentPages", (string)null);
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.EligibilityRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Assessment", "BenefitsIntelligence.Domain.Policies.EligibilityRule.Assessment#FactAssessment", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Confidence")
                                .HasColumnType("float")
                                .HasColumnName("Confidence");

                            b1.Property<int>("ReviewReasons")
                                .HasColumnType("int")
                                .HasColumnName("ReviewReasons");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Evidence", "BenefitsIntelligence.Domain.Policies.EligibilityRule.Assessment#FactAssessment.Evidence#Evidence", b2 =>
                                {
                                    b2.Property<int>("PageEnd")
                                        .HasColumnType("int")
                                        .HasColumnName("EvidencePageEnd");

                                    b2.Property<int>("PageStart")
                                        .HasColumnType("int")
                                        .HasColumnName("EvidencePageStart");

                                    b2.Property<string>("Quote")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("nvarchar(2000)")
                                        .HasColumnName("EvidenceQuote");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("PolicyId", "Type")
                        .IsUnique();

                    b.ToTable("EligibilityRules", (string)null);
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.PolicyDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("PolicyDocuments");
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.PolicyFieldAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Field")
                        .HasColumnType("int");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Assessment", "BenefitsIntelligence.Domain.Policies.PolicyFieldAssessment.Assessment#FactAssessment", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Confidence")
                                .HasColumnType("float")
                                .HasColumnName("Confidence");

                            b1.Property<int>("ReviewReasons")
                                .HasColumnType("int")
                                .HasColumnName("ReviewReasons");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Evidence", "BenefitsIntelligence.Domain.Policies.PolicyFieldAssessment.Assessment#FactAssessment.Evidence#Evidence", b2 =>
                                {
                                    b2.Property<int>("PageEnd")
                                        .HasColumnType("int")
                                        .HasColumnName("EvidencePageEnd");

                                    b2.Property<int>("PageStart")
                                        .HasColumnType("int")
                                        .HasColumnName("EvidencePageStart");

                                    b2.Property<string>("Quote")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("nvarchar(2000)")
                                        .HasColumnName("EvidenceQuote");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("PolicyId", "Field")
                        .IsUnique();

                    b.ToTable("PolicyFieldAssessments", (string)null);
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Processing.ProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("PolicyId", "CreatedAt");

                    b.ToTable("ProcessingJobs");
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.BenefitPolicy", b =>
                {
                    b.HasOne("BenefitsIntelligence.Domain.Policies.PolicyDocument", null)
                        .WithOne()
                        .HasForeignKey("BenefitsIntelligence.Domain.Policies.BenefitPolicy", "DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BenefitsIntelligence.Domain.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.CoverageItem", b =>
                {
                    b.HasOne("BenefitsIntelligence.Domain.Policies.BenefitPolicy", null)
                        .WithMany("CoverageItems")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.DocumentPage", b =>
                {
                    b.HasOne("BenefitsIntelligence.Domain.Policies.PolicyDocument", null)
                        .WithMany("Pages")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.EligibilityRule", b =>
                {
                    b.HasOne("BenefitsIntelligence.Domain.Policies.BenefitPolicy", null)
                        .WithMany("EligibilityRules")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.PolicyDocument", b =>
                {
                    b.HasOne("BenefitsIntelligence.Domain.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.PolicyFieldAssessment", b =>
                {
                    b.HasOne("BenefitsIntelligence.Domain.Policies.BenefitPolicy", null)
                        .WithMany("FieldAssessments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Processing.ProcessingJob", b =>
                {
                    b.HasOne("BenefitsIntelligence.Domain.Policies.BenefitPolicy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.BenefitPolicy", b =>
                {
                    b.Navigation("CoverageItems");

                    b.Navigation("EligibilityRules");

                    b.Navigation("FieldAssessments");
                });

            modelBuilder.Entity("BenefitsIntelligence.Domain.Policies.PolicyDocument", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
