@BenefitsIntelligence.Api_HostAddress = http://localhost:5209

GET {{BenefitsIntelligence.Api_HostAddress}}/health

###

GET {{BenefitsIntelligence.Api_HostAddress}}/api/policies

###

@policyId = 00000000-0000-0000-0000-000000000000

GET {{BenefitsIntelligence.Api_HostAddress}}/api/policies/{{policyId}}

###
